project:
  type: website
  output-dir: ../docs

website:
  title: "Scott's Data Science Blog"
  site-url: htts://www.swied.com
  google-analytics: "G-ZZ12P3MMWN"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  comments:
    giscus:
      repo: swied/swied-website
listing:
  contents: posts
  feed: true
format:
  html:
    theme: flatly
    css: styles.css



