project:
  type: website
  output-dir: ../docs

website:
  title: "Scott Wied's Data Science Blog"
  google-analytics: "G-ZZ12P3MMWN"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/scottwied
format:
  html:
    theme: flatly
    css: styles.css



